### ISSUE TITLE
Migration to GitHub Pages

### ISSUE THREAD

**Issue by raimis** [openmm/openmm-org#49] opened 2021-05-20 14:08 UTC
In preparation to the new website (#45), we need to move to the GitHub Pages (https://docs.github.com/en/pages). Apparently, even the current (old) website works fine on the GitHub Pages: https://openmm.github.io/openmm-org/

To complete the migration, the DNS record of [openmm.org](openmm.org) has to be update: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain

As a bonus, this will solve the HTTPS issue (#38).

**Comment by raimis** [comment] 2021-05-20 14:09
@jchodera, as I remember, you have access to the domain records.

**Comment by jchodera** [comment] 2021-05-20 17:58
Yes! I can do this if we're ready to go!

@peastman @Yoshanuikabundi : Do you think we're ready to go now?

**Comment by jchodera** [comment] 2021-05-20 20:05
The only thing I noted is that the Markdown renderer does not do syntax highlighting, but this is minor and something we can fix.

Thanks so much for all the effort you put into this, @raimis! I'll switch this today and report back!

**Comment by Yoshanuikabundi** [comment] 2021-05-21 04:01
Looks good! The docs are still served over HTTP rather than HTTPS, so they're not being rendered with GitHub Pages - I'm sure you all know that but I'm mentioning it in case it suggests to someone with more knowledge about how everything is served that something is wrong.

**Comment by jchodera** [comment] 2021-05-21 04:28
> The docs are still served over HTTP rather than HTTPS, so they're not being rendered with GitHub Pages - I'm sure you all know that but I'm mentioning it in case it suggests to someone with more knowledge about how everything is served that something is wrong.

@Yoshanuikabundi : That's a great point! Can you open an issue to remind us about this?

**Comment by jchodera** [comment] 2021-05-24 21:18
@peastman @raimis I'm starting the DNS migration/update now.

**Comment by jchodera** [comment] 2021-05-24 21:31
Migration complete! Let me know if you notice anything broken with the DNS.

For reference: I've deleted the AWS Route 53 zone that was previously serving our DNS and switched to GoDaddy's DNS servers, following the [instructions](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain) linked by @raimis to activate custom GitHub Pages domains.

**Comment by jchodera** [comment] 2021-05-24 21:34
It looks like everything at docs.openmm.org (which is still hosted on S3) appears to be broken.

Let me see if I can fix that with GoDaddy's DNS. Otherwise, I'll migrate back to Route 53 DNS and just serve DNS from that.

**Comment by jchodera** [comment] 2021-05-24 21:42
For reference, here are the old AWS Route 53 records:
![image](https://user-images.githubusercontent.com/3656088/119410746-2a920780-bc9e-11eb-8225-0ef54dbf44f1.png)

And here are my updated GoDaddy records:
![image](https://user-images.githubusercontent.com/3656088/119410636-06362b00-bc9e-11eb-958e-f538882956c5.png)

I'm still seeing issues with docs.openmm.org and the docs pages within, but I'm not sure if this is due to (1) DNS propagation delay, (2) the docs pages specifying a root URL that is on a different site, or (3) something else I don't know about.

I'll revert this change if the DNS doesn't pick up and fix things in 30 min.

I've already tweeted about the disruption:
https://twitter.com/openmm_toolkit/status/1396942413449498624

**Comment by jchodera** [comment] 2021-05-24 22:08
Looks like this is not working at all now, so I will likely need to revert back.

**Comment by jchodera** [comment] 2021-05-24 22:46
openmm.org is working now that I've changed the GoDaddy records, but I'm still not able to get the docs pages to work:
![image](https://user-images.githubusercontent.com/3656088/119415714-04249a00-bca7-11eb-9262-4b124f9301b8.png)
Any ideas? 

URLs like http://docs.openmm.org/latest/userguide/index.html are not correctly being redirected to http://docs.openmm.org.s3-website-us-west-1.amazonaws.com/latest/userguide/index.html

**Comment by peastman** [comment] 2021-05-24 23:10
The docs are working for me.  I don't know whether that's because something cached somewhere hasn't propagated to me yet, or because you needed to wait a little longer for a cache to update for you.  I'll check again in a little while and see if it's still working.

**Comment by jchodera** [comment] 2021-05-24 23:34
OK, they started working when I made this change:
![image](https://user-images.githubusercontent.com/3656088/119418861-d5f68880-bcad-11eb-800b-68f4016e6d30.png)

It looks like they're still not `https`, however.

**Comment by jchodera** [comment] 2021-05-25 16:06
Closing this since migration is complete, and http/https issue is separated into #50.

**Comment by raimis** [comment] 2021-05-26 09:51
[builder.openmm.org ](http://builder.openmm.org)seems to be broken:

```
$ curl -I builder.openmm.org
HTTP/1.1 400 Bad Request
x-amz-error-code: IncorrectEndpoint
x-amz-error-message: The specified bucket exists in another region. Please direct requests to the specified endpoint.
x-amz-error-detail-Endpoint: builder.openmm.org.s3-website-us-east-1.amazonaws.com
x-amz-request-id: ZM8ATANR65YABFH0
x-amz-id-2: raG/lgw3wiC++jGCCDwbXDA+Ls9Pmrgjiu644hRtnbhgvMUDT54iiVAPEbDel4wXP9Vu3JNKSlU=
Date: Wed, 26 May 2021 09:48:24 GMT
Server: AmazonS3
Connection: close
```

This might be not a DNS issue.

**Comment by peastman** [comment] 2021-05-26 16:01
Where did you find a reference to builder.openmm.org?  It hasn't been supported in many years.

**Comment by jchodera** [comment] 2021-05-26 16:17
I spotted an error in the DNS entry. I've made the fix, and we'll see if it starts working soon.

**Comment by jchodera** [comment] 2021-05-26 17:19
http://builder.openmm.org is working once again! The issue was that the DNS entry was pointing to a bucket in the wrong region. For some reason, builder is in `us-east-1` and the docs bucket is in `us-west-1`!

Please reopen if this is not resolved.

**Closed by jchodera** 2021-05-26 17:19 UTC

**Comment by peastman** [comment] 2021-05-26 17:25
Please make it stop working again!  Like I said, it hasn't been supported in years.  Where is it being served from?  We should track it down and, if possible, take it down.

**Comment by jchodera** [comment] 2021-05-26 17:46
Whoops! Next time, could you be explicit about what you think the intended behavior should be, @peastman?

How would you like me to deactivate it?
1. Remove the DNS entry and tweet that we are no longer supporting it
2. Blow away the S3 bucket containing it as well
3. Something else?

**Comment by peastman** [comment] 2021-05-26 18:17
Remove the DNS.  I don't think there's anything to tweet.  We haven't supported it in many years.  It's been a long time since it actually produced correct code.  So far as I know, we removed all references to it from our website years ago.  That's why I asked @raimis how he even knew it existed.  Where did you find a reference to it?

**Comment by raimis** [comment] 2021-05-26 18:23
>  That's why I asked @raimis how he even knew it existed. Where did you find a reference to it?

@peastman, it shows up frequent, if searching something about OpenMM on Google.

**Comment by jchodera** [comment] 2021-05-26 19:58
@peastman : I've deleted the builder DNS entry and deleted my tweet about having fixed the builder following DNS migration.

What should we do about the frequent search hits?

**Comment by peastman** [comment] 2021-05-26 20:02
How very annoying!  Let's make sure none of our websites have links to it anywhere.  Once the URL no longer works, hopefully Google will figure out quickly to stop directing people to it.
